# Generated by Django 5.2.16 on 2026-07-12 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('readings', '0005_rename_metrics_2'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('time', models.DateTimeField(primary_key=True, serialize=False)),
                ('device_id', models.CharField(max_length=128)),
                ('metric', models.CharField(max_length=64)),
                ('value', models.FloatField()),
            ],
            options={
                'db_table': 'readings_sensorreading',
                'ordering': ['-time'],
                'managed': False,
            },
        ),
    ]
