# Generated by Django 5.2.15 on 2026-07-09 20:21

import django.core.validators
import django.db.models.deletion
import ota.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HardwareCode',
            fields=[
                ('hw_code', models.CharField(max_length=8, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^[A-Z0-9]{8}$', message='Hardware code must be exactly 8 uppercase alphanumeric characters.')])),
                ('platform', models.CharField(blank=True, default='', max_length=32)),
                ('description', models.CharField(blank=True, default='', max_length=256)),
                ('modules', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'hardware code',
                'verbose_name_plural': 'hardware codes',
                'ordering': ['hw_code'],
            },
        ),
        migrations.CreateModel(
            name='HardwareRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hw_rev', models.PositiveSmallIntegerField()),
                ('description', models.CharField(blank=True, default='', max_length=256)),
                ('bat_divider_nominal', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hardware_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='ota.hardwarecode')),
            ],
            options={
                'verbose_name': 'hardware revision',
                'verbose_name_plural': 'hardware revisions',
                'ordering': ['hardware_code', 'hw_rev'],
            },
        ),
        migrations.CreateModel(
            name='Firmware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=32)),
                ('file', models.FileField(upload_to=ota.models.firmware_upload_path)),
                ('md5', models.CharField(max_length=32)),
                ('size', models.PositiveIntegerField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('hardware_revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='firmwares', to='ota.hardwarerevision')),
            ],
            options={
                'verbose_name': 'firmware',
                'verbose_name_plural': 'firmwares',
                'ordering': ['hardware_revision', '-uploaded_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='hardwarerevision',
            constraint=models.UniqueConstraint(fields=('hardware_code', 'hw_rev'), name='unique_hw_code_rev'),
        ),
        migrations.AddConstraint(
            model_name='firmware',
            constraint=models.UniqueConstraint(fields=('hardware_revision', 'version'), name='unique_firmware_rev_version'),
        ),
    ]
