# Generated by Django 5.2.16 on 2026-07-11 12:56

import catalog.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ota', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('summary', models.CharField(blank=True, default='', max_length=256)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('deprecated', 'Deprecated')], default='draft', max_length=16)),
                ('body', models.TextField(blank=True, default='')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='catalog/covers/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hardware_codes', models.ManyToManyField(blank=True, related_name='sensor_designs', to='ota.hardwarecode')),
            ],
            options={
                'verbose_name': 'sensor design',
                'verbose_name_plural': 'sensor designs',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SensorImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=catalog.models.sensor_image_path)),
                ('caption', models.CharField(blank=True, default='', max_length=256)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.sensordesign')),
            ],
            options={
                'verbose_name': 'sensor image',
                'verbose_name_plural': 'sensor images',
                'ordering': ['uploaded_at'],
            },
        ),
    ]
