# Generated by Django 5.2.13 on 2026-04-14 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0005_device_location_type'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='devicestatuslog',
            new_name='devices_dev_device__cca2a5_idx',
            old_name='devices_dev_device__6d13fb_idx',
        ),
        migrations.AddField(
            model_name='device',
            name='battery_cell_count',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
