# Generated by Django 5.2.15 on 2026-07-09 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0008_commandlog_status'),
        ('ota', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='hw_code',
        ),
        migrations.AddField(
            model_name='device',
            name='calibration',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='device',
            name='hardware_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='ota.hardwarecode'),
        ),
        migrations.AddField(
            model_name='device',
            name='hw_rev',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='ota_capable',
            field=models.BooleanField(default=False),
        ),
    ]
