# Generated by Django 5.2.16 on 2026-07-12 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(blank=True, choices=[('guest', 'Guest'), ('resident', 'Resident'), ('admin', 'Administrator')], default=None, max_length=10, null=True),
        ),
    ]
